### ISSUE TITLE
Installation: Unexpected end of JSON input while parsing near '....10"

### ISSUE THREAD

**Issue by 7clouda** [VenkSociety/Tsuyo#23]
npm ERR! Unexpected end of JSON input while parsing near '....10"
npm ERR!     }
npm ERR!   }
npm ERR! }
npm ERR! '

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\winterdev.ru\AppData\Roaming\npm-cache\_logs\2020-05-15T18_11_36_446Z-debug.log

**Comment by VenkSociety** [comment]
1593ab7 should fix this. If nor, try deleting your `package-lock.json` file.
